services:
  waha:
    image: devlikeapro/waha
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - WHATSAPP_DEFAULT_ENGINE=NOWEB
    volumes:
      - ./.waha:/app/.waha
    restart: unless-stopped
